my %targets = (
    "conan-Release-Linux-x86_64-gcc-11" => {
        inherit_from => [ "linux-x86_64" ],
        cflags => add("-m64 -fPIC -O3"),
        cxxflags => add("-m64 -fPIC -O3"),
        defines => add("NDEBUG"),
        lflags => add("-m64"),
        
        
        
        
    },
);
